import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const api = read('src/services/api.ts')
const conversation = read('src/pages/conversation/index.tsx')
const conversationStyles = read('src/pages/conversation/index.module.scss')
const hub = read('src/pages/hub/index.tsx')
const article = read('src/pages/article/index.tsx')
const types = read('src/types/pinco.ts')
const store = read('src/store/usePincoStore.ts')
const membership = read('src/pages/membership/index.tsx')
const experts = read('src/pages/experts/index.tsx')
const jobSearch = read('src/pages/job-search/index.tsx')
const home = read('src/pages/home/index.tsx')
const mine = read('src/pages/mine/index.tsx')
const career = read('src/pages/career/index.tsx')
const expertCenter = read('src/pages/expert-center/index.tsx')

const requiredPostTypes = ['treehole', 'help', 'share', 'success']

for (const type of requiredPostTypes) {
  assert.match(types, new RegExp(`'${type}'`), `PostType must include ${type}`)
  assert.match(hub, new RegExp(`'${type}'`), `Hub publish UI must include ${type}`)
}

assert.match(hub, /📚 干货/, 'Publish modal must show 干货')
assert.match(hub, /🎉 上岸/, 'Publish modal must show 上岸')
assert.match(hub, /postContentInput[\s\S]*关联岗位（可选[\s\S]*postModalButtons/, 'Job binding must be selectable inside the publish modal')
assert.doesNotMatch(hub, /commentInput[\s\S]{0,1800}关联岗位（可选/, 'Comment composer must not contain the post-level job selector')
assert.match(hub, /经验标签（可选，帮助其他人判断是否适用）/, 'High-value community posts must support round and time metadata')
assert.doesNotMatch(hub, /请先登录|先登录/, 'Summon must not block anonymous users')

assert.match(api, /wx\.cloud\.callContainer/, 'WeChat runtime must use wx.cloud.callContainer')
assert.doesNotMatch(api, /process\.env\.NODE_ENV === 'development'[\s\S]{0,120}127\.0\.0\.1:8090/, 'WeChat development builds must not point real devices at localhost')
assert.doesNotMatch(
  api,
  /canUseCallContainer\(\)\s*&&\s*process\.env\.NODE_ENV\s*!==\s*'development'/,
  'WeChat devtools must still use callContainer instead of falling back to invalid request domains'
)
assert.match(api, /encoding:\s*'base64'/, 'Uploads must read selected files as base64')
assert.match(api, /res\.statusCode === 401[\s\S]*recoverApiSession\(\)/, 'callContainer 401 must recover the user session')
assert.match(api, /response\.statusCode === 401[\s\S]*recoverApiSession\(\)/, 'HTTP 401 must recover the user session')
assert.match(api, /return apiRequestInternal<T>\(retry\.path, method, retry\.data, false\)/, 'Session recovery must retry only once')
assert.match(api, /nextData\.user_id = replaceClaim/, 'Recovered requests must replace the stale user id')
assert.match(api, /envVersion === 'develop'[\s\S]*__pincoExpireSessionForTest/, 'Session expiry regression hook must be limited to WeChat develop builds')

assert.match(conversation, /getClipboardData/, 'Copy must verify clipboard content after setting it')
assert.doesNotMatch(conversation, /onTouchStart=\{startRecord\}/, 'Voice button must not mix native touch and synthetic click recording paths')
assert.doesNotMatch(conversation, /onTouchEnd=\{stopRecord\}/, 'Voice button must use one tap state machine instead of long-press release handling')
assert.match(conversation, /micBody/, 'Voice button must render custom line icon')
assert.match(conversation, /recordStartPendingRef[\s\S]*nativeRecorderStartedRef/, 'Voice state must distinguish an async start from an active native recording')
assert.match(conversation, /recorderManager\.offStart\?\.\(\)/, 'Global recorder callbacks must be removed when the page unmounts')
assert.match(conversation, /voiceMessageModeRef/, 'Recorder callbacks must read current voice mode without re-registering listeners')
assert.match(conversation, /mask:\s*false/, 'ASR processing must not block the entire chat page')
assert.match(conversation, /ariaLabel=\{isRecording \? '正在录音，再点一次发送' : '录音'\}/, 'Voice button must expose an accessible label')
assert.match(conversation, /voiceAccessibleLabel/, 'Voice button must keep an accessibility-tree text label')
assert.match(conversation, /chooseimage[\s\S]*选择或拍摄图片/, 'Privacy prompt must describe image selection accurately')
assert.match(conversation, /choosemessagefile[\s\S]*PDF 或 DOCX/, 'Privacy prompt must describe resume file selection accurately')
assert.match(conversation, /主动触发当前功能/, 'Unknown privacy referrers must not be mislabeled as clipboard access')
assert.match(conversation, /全选输入内容/, 'The chat composer must expose a visible select-all action')
assert.match(conversation, /selectionStart=\{draftSelection\.start\}/, 'Select-all must drive the native textarea selection range')
assert.match(conversation, /onLongPress=.*setMessageActionTarget/s, 'Assistant answers must open an action menu on long press')
assert.match(conversation, /选择文本/, 'The long-press menu must support selective copying')
assert.match(conversation, /handleRegenerate/, 'The long-press menu must support real regeneration')
assert.match(store, /regenerateMessage:[\s\S]*\/api\/v1\/chat/, 'Regeneration must call the real model endpoint without adding a fake user turn')
assert.match(conversationStyles, /\.recordOverlay[\s\S]*pointer-events:\s*none/, 'Recording status must never block release or second-tap events')

assert.match(hub, /<Input[\s\S]*className=\{styles\.postTitleInput\}/, 'Publish titles must use a stable single-line input')
assert.match(hub, /className=\{styles\.postContentInput\}[\s\S]*fixed/, 'The fixed publish modal must mark its textarea as fixed')
assert.doesNotMatch(hub, /navigateTo\([\s\S]{0,120}pages\/conversation\/index/, 'Community actions must not use navigateTo for a tab page')
assert.match(hub, /switchTab\(\{ url: '\/pages\/conversation\/index'/, 'Community practice must switch to the conversation tab')
assert.match(article, /switchTab\(\{ url: '\/pages\/conversation\/index'/, 'Article practice must switch to the conversation tab')
assert.match(article, /seedConversation\('garden'/, 'Article practice must seed a real exercise after switching tabs')

assert.match(expertCenter, /Promise\.allSettled/, 'Expert status and workspace loading must not take down the whole page together')
assert.match(expertCenter, /intro\.trim\(\)\.length < 20/, 'Expert applications must validate minimum intro length before submitting')
assert.match(expertCenter, /proof.*https?:/is, 'Expert applications must validate proof URLs before submitting')

assert.doesNotMatch(store, /我先基于你发来的岗位描述做本地拆解/, 'JD failure must not look like a completed analysis')
assert.match(store, /模拟面试没有启动成功/, 'Interview failure must be explicit')
assert.match(store, /user_id:\s*get\(\)\.userProfile\?\.user_id/, 'Chat turns must carry the authenticated user id')
assert.doesNotMatch(store, /const inferJobEvent/, 'Progress prompts must be decided by the server agent, not local keyword rules')
assert.match(store, /progress_suggestion/, 'The client must consume model-planned progress suggestions')
assert.match(store, /trackProductEvent\('chat\.send\.failed'/, 'Critical chat failures must be measured')
assert.match(store, /setApiSessionRecoveryHandler\(async \(\) =>/, 'The store must register automatic session recovery')
assert.match(store, /userProfile: data\.user/, 'Recovered sessions must update the active user profile')
assert.match(membership, /登记开通意向（不扣款）/, 'Membership must disclose unavailable real payment')
assert.match(membership, /Taro\.requestPayment/, 'Purchasable membership must use the WeChat cashier API')
assert.match(membership, /fetchPaymentOrder/, 'Membership activation must wait for a server-side payment query')
assert.match(membership, /closePaymentOrder/, 'Canceled cashier sessions must be reconciled and closed')
assert.match(membership, /fetchPaymentOrders/, 'Membership page must recover unfinished orders after a restart')
assert.match(membership, /status === 'paid' && confirmed\.fulfilled/, 'Client success alone must never claim membership activation')
assert.match(membership, /本期额度重置时间/, 'Membership usage must disclose the server-side reset window')
assert.match(experts, /提交预约意向（不扣款）/, 'Expert flow must not pretend payment succeeded')
assert.match(mine, /payExpert/, 'Confirmed expert bookings must expose the guarded payment flow')
assert.match(mine, /refundPaymentOrder/, 'Paid unfinished expert services must expose server-side refund handling')
assert.match(mine, /reconcileExpertPayment/, 'Expert payment retries must reconcile or close the previous order first')
assert.equal(fs.existsSync(path.join(root, 'src/data/experts.ts')), false, 'Static expert candidates must not ship')
assert.equal(fs.existsSync(path.join(root, 'src/data/community.ts')), false, 'Static community interactions must not ship')
assert.match(jobSearch, /job\.verified_source\s*&&\s*job\.url/, 'Job cards must require a verified source URL')
assert.match(jobSearch, /带来源候选，请打开确认在招/, 'Job cards must not claim a source-linked candidate is definitely active')
assert.match(career, /学姐记住的职业信息/, 'Users must be able to see the career facts used by the Agent')
assert.match(career, /workspace\/memory\/forget/, 'Users must be able to forget an individual Agent memory')
assert.doesNotMatch(jobSearch, /公司官网、脉脉、猎聘多平台搜索/, 'UI must not advertise an unavailable official-site provider')
assert.match(conversation, /\[5, 10, 20, 30\]/, 'Interview practice must offer 5/10/20/30 minute modes')
assert.match(conversation, /陪我热身/, 'Interview practice must offer a warm-up intensity')
assert.match(conversation, /真实强度/, 'Interview practice must offer realistic intensity')
assert.match(conversation, /压力追问/, 'Interview practice must offer pressure follow-ups')
assert.match(conversation, /给我一个救场框架/, 'Active practice must expose a non-advancing rescue scaffold')
assert.match(store, /\/rescue/, 'Interview rescue must use the structured backend endpoint')
assert.match(store, /interview\.practice\.completed/, 'Completed interview practice must be measured')
assert.match(store, /\/api\/v1\/interview\/practice\//, 'Interview answers must use the structured practice API')
assert.match(home, /今天状态怎么样/, 'Home must expose emotional check-in across the product')
assert.match(home, /昨天约定的小行动完成了吗/, 'Follow-up must ask for a real 24-hour micro-action result')
assert.match(store, /micro_action_completed:\s*microActionCompleted/, 'Micro-action completion must persist to the backend')
assert.match(conversation, /被理解了/, 'Emotional support must capture whether the user felt understood')
assert.match(store, /understood_score:\s*understoodScore/, 'Understood score must persist to the backend')
assert.doesNotMatch(store, /trackProductEvent\('emotion\.support_feedback'/, 'Support feedback must not be double-counted by client and backend')
assert.match(mine, /先听我说/, 'Users must be able to choose their support style')
assert.match(mine, /允许记住倾诉正文/, 'Emotional memory must require explicit consent')
assert.match(mine, /首批用户共创/, 'First users must have an in-product design-partner feedback entry')
assert.match(mine, /professional_value_score/, 'Pilot feedback must measure professional value')
assert.match(mine, /emotional_value_score/, 'Pilot feedback must measure emotional value')
assert.match(mine, /未来 7 天，你会继续使用 Pinco 吗/, 'Pilot feedback must capture near-term return intent')
assert.match(mine, /\/api\/v1\/pilot\/feedback/, 'Pilot feedback must persist to the backend')
assert.match(store, /pending\.status === 'rejected'/, 'Job rejection must trigger a support action')
assert.match(career, /求职证据库/, 'Career evidence workspace must be available')
assert.match(career, /不得编经历|不能替你编经历|不会替你编经历/, 'Evidence workspace must state the truth boundary')
assert.doesNotMatch(career, /jd_text=\$\{encodeURIComponent\(job\.jd_text\)\}/, 'Job practice links must not embed a full JD in the WeChat navigation URL')
assert.match(career, /response\.support_action/, 'Career status changes must offer contextual emotional support')
assert.match(career, /本周 7 天证据补缺/, 'Career workspace must expose the cross-job seven-day gap plan')
assert.match(career, /workspace\/learning-plan\/progress/, 'Seven-day plan completion must persist to the backend')
assert.match(career, /匿名发布结构化复盘/, 'Completed interview reports must be able to flow back into the community')
assert.match(career, /不会公开你的原始回答、姓名或会话全文/, 'Interview report publishing must disclose its privacy boundary')
assert.match(experts, /会前摘要授权（可选）/, 'Expert context sharing must require visible per-booking consent')
assert.match(experts, /不会分享会话全文或账号数据/, 'Expert context sharing must disclose its privacy boundary')
assert.match(expertCenter, /用户已授权的会前摘要/, 'Experts must see the consented briefing before service')
assert.match(expertCenter, /用户下一步行动，每行一条/, 'Expert delivery must capture an actionable follow-up list')
assert.match(mine, /下一步 \{index \+ 1\}/, 'Buyers must receive expert next actions')
assert.match(jobSearch, /保存岗位/, 'Verified search results must flow into the job workspace')

console.log('critical-flows static checks passed')
