import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const api = read('src/services/api.ts')
const conversation = read('src/pages/conversation/index.tsx')
const conversationStyles = read('src/pages/conversation/index.module.scss')
const hub = read('src/pages/hub/index.tsx')
const article = read('src/pages/article/index.tsx')
const types = read('src/types/pinco.ts')
const store = read('src/store/usePincoStore.ts')
const membership = read('src/pages/membership/index.tsx')
const experts = read('src/pages/experts/index.tsx')
const jobSearch = read('src/pages/job-search/index.tsx')
const home = read('src/pages/home/index.tsx')
const mine = read('src/pages/mine/index.tsx')
const career = read('src/pages/career/index.tsx')
const expertCenter = read('src/pages/expert-center/index.tsx')
const bookingChat = read('src/pages/booking-chat/index.tsx')
const appConfig = read('src/app.config.ts')

const requiredPostTypes = ['treehole', 'help', 'share', 'success']

for (const type of requiredPostTypes) {
  assert.match(types, new RegExp(`'${type}'`), `PostType must include ${type}`)
  assert.match(hub, new RegExp(`'${type}'`), `Hub publish UI must include ${type}`)
}

assert.match(hub, /干货/, 'Publish modal must show 干货')
assert.match(hub, /🎉 上岸/, 'Publish modal must show 上岸')
assert.match(hub, /postContentInput[\s\S]*关联岗位（可选[\s\S]*postModalButtons/, 'Job binding must be selectable inside the publish modal')
assert.doesNotMatch(hub, /commentInput[\s\S]{0,1800}关联岗位（可选/, 'Comment composer must not contain the post-level job selector')
assert.match(hub, /经验标签（可选，帮助其他人判断是否适用）/, 'High-value community posts must support round and time metadata')
assert.doesNotMatch(hub, /请先登录|先登录/, 'Summon must not block anonymous users')
assert.match(hub, /useEffect\(\(\) => \{[\s\S]{0,120}userProfile\?\.user_id[\s\S]{0,80}loadPosts\(\)/, 'Community must reload after async identity bootstrap')
assert.match(hub, /ensureCommunityUserId[\s\S]*await bootstrap\(\)[\s\S]*身份初始化失败，请检查网络后重试[\s\S]*return userId/, 'Community actions must recover identity before blocking the user')
for (const action of ['publishPost', 'handleLike', 'submitComment', 'handleHug', 'handleSummon', 'handleReport', 'turnPostIntoAction']) {
  assert.match(hub, new RegExp(`const ${action} = async[\\s\\S]{0,900}ensureCommunityUserId\\(\\)`), `${action} must retry identity bootstrap before calling a community endpoint`)
}
assert.match(hub, /activeFilter === 'all'[\s\S]{0,100}articles: \[\]/, 'All must be a community feed instead of duplicating the editorial tab')
assert.match(hub, /activeFilter === 'article'[\s\S]{0,160}isFeatured/, 'Featured must combine editorial knowledge with explicitly featured discussions')

assert.match(api, /wx\.cloud\.callContainer/, 'WeChat runtime must use wx.cloud.callContainer')
assert.doesNotMatch(api, /process\.env\.NODE_ENV === 'development'[\s\S]{0,120}127\.0\.0\.1:8090/, 'WeChat development builds must not point real devices at localhost')
assert.doesNotMatch(
  api,
  /canUseCallContainer\(\)\s*&&\s*process\.env\.NODE_ENV\s*!==\s*'development'/,
  'WeChat devtools must still use callContainer instead of falling back to invalid request domains'
)
assert.match(api, /encoding:\s*'base64'/, 'Uploads must read selected files as base64')
assert.match(api, /res\.statusCode === 401[\s\S]*recoverApiSession\(\)/, 'callContainer 401 must recover the user session')
assert.match(api, /response\.statusCode === 401[\s\S]*recoverApiSession\(\)/, 'HTTP 401 must recover the user session')
assert.match(api, /return apiRequestInternal<T>\(retry\.path, method, retry\.data, false\)/, 'Session recovery must retry only once')
assert.match(api, /nextData\.user_id = replaceClaim/, 'Recovered requests must replace the stale user id')
assert.match(api, /envVersion === 'develop'[\s\S]*__pincoExpireSessionForTest/, 'Session expiry regression hook must be limited to WeChat develop builds')

assert.match(conversation, /getClipboardData/, 'Copy must verify clipboard content after setting it')
assert.doesNotMatch(conversation, /onTouchStart=\{startRecord\}/, 'Voice button must not mix native touch and synthetic click recording paths')
assert.doesNotMatch(conversation, /onTouchEnd=\{stopRecord\}/, 'Voice button must use one tap state machine instead of long-press release handling')
assert.match(conversation, /micBody/, 'Voice button must render custom line icon')
assert.match(conversation, /recordStartPendingRef[\s\S]*nativeRecorderStartedRef/, 'Voice state must distinguish an async start from an active native recording')
assert.match(conversation, /voice authorization timed out[\s\S]{0,220}finish\(false\)/, 'Voice privacy authorization must fail closed instead of leaving the button stuck')
assert.match(conversation, /recorderManager\.offStart\?\.\(\)/, 'Global recorder callbacks must be removed when the page unmounts')
assert.match(conversation, /recordLifecycleActiveRef\.current = false[\s\S]{0,900}recorderManager\.stop\(\)/, 'Unmounting must discard and stop the global recorder instead of leaving a hidden recording session')
assert.match(conversation, /useDidHide\(\(\) => \{[\s\S]{0,500}discardAndStopRecording\('page hide'\)/, 'Switching away from the cached chat tab must discard and stop background recording')
assert.match(conversation, /useDidShow\(\(\) => \{[\s\S]{0,120}recordLifecycleActiveRef\.current = true/, 'Returning to the chat tab must restore the recording lifecycle')
assert.match(conversation, /getCurrentPages[\s\S]{0,500}pages\/conversation\/index/, 'Recording must independently verify that the conversation route is still active')
assert.match(conversation, /setInterval\(\(\) => \{[\s\S]{0,500}discardAndStopRecording\('route change'\)/, 'A route watchdog must stop recording when cached tab lifecycle events are missed')
assert.match(conversation, /return \(\) => \{[\s\S]{0,180}clearRecordRouteWatch\(\)[\s\S]{0,1600}recorderManager\.offStart/, 'Unmounting must clear the recording route watchdog')
assert.match(conversation, /authorized = await ensurePrivacyAuthorized\(\)[\s\S]{0,300}!recordLifecycleActiveRef\.current/, 'Late privacy callbacks must not start recording after the chat page unmounts')
assert.match(conversation, /voiceMessageModeRef/, 'Recorder callbacks must read current voice mode without re-registering listeners')
assert.match(conversation, /mask:\s*false/, 'ASR processing must not block the entire chat page')
assert.match(conversation, /ariaLabel=\{isRecording \? '正在录音，再点一次发送' : '录音'\}/, 'Voice button must expose an accessible label')
assert.match(conversation, /voiceAccessibleLabel/, 'Voice button must keep an accessibility-tree text label')
assert.match(conversation, /chooseimage[\s\S]*选择或拍摄图片/, 'Privacy prompt must describe image selection accurately')
assert.match(conversation, /data\.extracted_text/, 'Image uploads must consume locally extracted text')
assert.match(conversation, /type:\s*'image',[\s\S]{0,120}user_id:\s*userProfile\?\.user_id/, 'Image OCR must require the active user session')
assert.match(conversation, /图片文字已填入输入框，请确认后发送/, 'OCR text must require user review before model submission')
assert.match(conversation, /maxlength=\{6000\}/, 'The composer must accept useful OCR and pasted JD text')
assert.match(conversation, /choosemessagefile[\s\S]*PDF 或 DOCX/, 'Privacy prompt must describe resume file selection accurately')
assert.match(conversation, /主动触发当前功能/, 'Unknown privacy referrers must not be mislabeled as clipboard access')
assert.match(conversation, /全选输入内容/, 'The chat composer must expose a visible select-all action')
assert.match(conversation, /selectionStart=\{draftSelection\.start\}/, 'Select-all must drive the native textarea selection range')
assert.doesNotMatch(conversation, /handleSelectAllDraft[\s\S]{0,220}setDraftFocused\(false\)/, 'Select-all must not create a WeChat blur race before applying its selection range')
assert.match(conversation, /handleSelectAllDraft[\s\S]{0,450}setTimeout[\s\S]{0,180}setDraftSelection\(\{ start: 0, end \}\)/, 'Select-all must reapply the native range after the button focus transition')
assert.match(conversation, /onLongPress=.*setMessageActionTarget/s, 'Assistant answers must open an action menu on long press')
assert.match(conversation, /选择文本/, 'The long-press menu must support selective copying')
assert.match(conversation, /handleRegenerate/, 'The long-press menu must support real regeneration')
assert.match(store, /regenerateMessage:[\s\S]*\/api\/v1\/chat/, 'Regeneration must call the real model endpoint without adding a fake user turn')
assert.match(conversationStyles, /\.recordOverlay[\s\S]*pointer-events:\s*none/, 'Recording status must never block release or second-tap events')
assert.match(conversation, /我还没有简历/, 'Golden path must support users without a current resume')
assert.match(conversation, /我有一份旧简历/, 'Golden path must reuse an old resume')
assert.match(conversation, /我不知道投什么/, 'Golden path must support direction discovery before job search')
assert.match(conversation, /我已有目标岗位/, 'Golden path must support a known target role or JD')
assert.match(conversation, /\/api\/v1\/workspace\/evidence\/draft/, 'Narrated experience must become a reviewable evidence draft')
assert.match(conversation, /\/api\/v1\/workspace\/evidence['"]/, 'Confirmed evidence must persist through the workspace endpoint')
assert.match(conversation, /这是待确认草稿|确认后才会保存/, 'The evidence builder must expose the draft truth boundary')
assert.match(conversation, /roleDirections[\s\S]*pages\/job-search\/index\?q=/, 'Role directions must flow into sourced job search')
assert.match(conversation, /voiceCaptureTargetRef[\s\S]*setEvidenceNarrative/, 'Evidence narration must receive ASR text without sending an unintended chat turn')
assert.match(store, /从旧简历提炼真实证据[\s\S]*build_evidence/, 'A parsed old resume must continue into evidence extraction')

assert.match(hub, /<Input[\s\S]*className=\{styles\.postTitleInput\}/, 'Publish titles must use a stable single-line input')
assert.match(hub, /className=\{styles\.postContentInput\}[\s\S]*fixed/, 'The fixed publish modal must mark its textarea as fixed')
assert.match(hub, /newPostTitleRef[\s\S]*newPostContentRef/, 'Publish fields must keep native drafts in refs')
assert.match(hub, /onInput=\{\(e\) => \{ newPostTitleRef\.current = e\.detail\.value \}\}/, 'Title input must not re-render the modal on each character')
assert.match(hub, /onInput=\{\(e\) => \{ newPostContentRef\.current = e\.detail\.value \}\}/, 'Content input must not re-render the modal on each character')
assert.doesNotMatch(hub, /className=\{styles\.post(?:Title|Content)Input\}[\s\S]{0,120}\bvalue=\{newPost/, 'Publish fields must not force stale controlled values into native inputs')
assert.match(hub, /post_type:\s*newPostType/, 'Publish must send the backend-compatible post type')
assert.doesNotMatch(hub, /navigateTo\([\s\S]{0,120}pages\/conversation\/index/, 'Community actions must not use navigateTo for a tab page')
assert.match(hub, /switchTab\(\{ url: '\/pages\/conversation\/index'/, 'Community practice must switch to the conversation tab')
assert.match(article, /switchTab\(\{ url: '\/pages\/conversation\/index'/, 'Article practice must switch to the conversation tab')
assert.match(article, /<Button[\s\S]{0,220}onClick=\{startArticlePractice\}/, 'Article practice entry must be a native accessible button')
assert.match(article, /未能打开练习，请重试/, 'Article practice navigation failures must be visible to the user')
assert.match(article, /const practiceTask = seedConversation[\s\S]{0,220}await Taro\.switchTab[\s\S]{0,160}await practiceTask/, 'Article practice must start before switching away from a page whose navigation promise may not resume')
assert.match(article, /seedConversation\('garden'/, 'Article practice must seed a real exercise after switching tabs')

assert.match(expertCenter, /Promise\.allSettled/, 'Expert status and workspace loading must not take down the whole page together')
assert.match(expertCenter, /intro\.trim\(\)\.length < 20/, 'Expert applications must validate minimum intro length before submitting')
assert.match(expertCenter, /proof.*https?:/is, 'Expert applications must validate proof URLs before submitting')
assert.match(expertCenter, /真实姓名（仅平台审核可见）/, 'Expert applications must separate legal identity from the public profile')
assert.match(expertCenter, /公开展示名/, 'Expert applications must collect a public display name')
assert.match(expertCenter, /candidate_alias/, 'The expert workbench must identify candidates by an anonymous booking alias')
assert.doesNotMatch(expertCenter, /确认并创建会议/, 'The expert action must not promise an unavailable automatic meeting')
assert.match(expertCenter, /confirmedSlots/, 'Experts must be able to confirm or adjust the requested time')
assert.match(expertCenter, /shareBookingContact/, 'Experts must be able to send a phone number or meeting link after accepting')
assert.match(expertCenter, /电话号码[\s\S]*会议链接/, 'Phone consultation must let the expert choose the contact method')
assert.match(expertCenter, /进入图文咨询/, 'Accepted chat consultations must open the in-app thread')

assert.doesNotMatch(store, /我先基于你发来的岗位描述做本地拆解/, 'JD failure must not look like a completed analysis')
assert.match(store, /模拟面试没有启动成功/, 'Interview failure must be explicit')
assert.match(store, /user_id:\s*get\(\)\.userProfile\?\.user_id/, 'Chat turns must carry the authenticated user id')
assert.doesNotMatch(store, /const inferJobEvent/, 'Progress prompts must be decided by the server agent, not local keyword rules')
assert.match(store, /progress_suggestion/, 'The client must consume model-planned progress suggestions')
assert.match(store, /trackProductEvent\('chat\.send\.failed'/, 'Critical chat failures must be measured')
assert.match(store, /setApiSessionRecoveryHandler\(async \(\) =>/, 'The store must register automatic session recovery')
assert.match(store, /userProfile: data\.user/, 'Recovered sessions must update the active user profile')
assert.doesNotMatch(appConfig, /pages\/membership\/index/, 'The 1.0 review build must not ship a virtual membership purchase page')
assert.doesNotMatch(mine, /requestPayment|payExpert|refundPaymentOrder|closePaymentOrder|升级会员|会员权益/, 'The 1.0 review build must not expose virtual purchase or payment controls')
assert.doesNotMatch(experts, /requestPayment|payExpert|¥|￥/, 'The 1.0 expert surface must not expose prices or payment controls')
assert.match(mine, /1\.0 免费公测/, 'The profile must clearly identify the free public beta')
assert.match(experts, /免费公测预约/, 'Expert booking must be presented as a free beta intent')
assert.match(experts, /默认以匿名身份预约/, 'Expert bookings must default to candidate anonymity')
assert.match(experts, /图文咨询[\s\S]*电话咨询/, 'Users must choose between in-app chat and phone consultation')
assert.match(experts, /consultation_type:\s*consultationType/, 'The selected consultation type must reach the backend')
assert.match(experts, /contact_wechat:\s*''/, 'The user must not be asked to expose contact information before acceptance')
assert.match(experts, /专家接受后[\s\S]*电话或会议链接/, 'Phone consultation must explain how contact is shared')
assert.match(mine, /进入图文咨询/, 'My bookings must expose the in-app chat entry')
assert.match(mine, /查看联系方式 \/ 咨询消息/, 'Phone bookings must expose the private contact thread')
assert.match(bookingChat, /fetchBookingMessages/, 'The consultation page must load the authorized booking thread')
assert.match(bookingChat, /sendBookingMessage/, 'The consultation page must send messages through the booking endpoint')
assert.match(bookingChat, /wx\.cloud\.uploadFile/, 'Chat images must upload to protected WeChat cloud storage')
assert.match(bookingChat, /仅本次预约的求职者和专家可见/, 'The chat UI must state its participant privacy boundary')
assert.match(bookingChat, /contact_value[\s\S]*setClipboardData/, 'Phone or meeting contact details must be copyable in the thread')
assert.match(appConfig, /pages\/booking-chat\/index/, 'The consultation message page must ship in the mini program')
assert.equal(fs.existsSync(path.join(root, 'src/data/experts.ts')), false, 'Static expert candidates must not ship')
assert.equal(fs.existsSync(path.join(root, 'src/data/community.ts')), false, 'Static community interactions must not ship')
assert.match(jobSearch, /job\.verified_source\s*&&\s*job\.url/, 'Job cards must require a verified source URL')
assert.match(jobSearch, /带来源候选，请打开确认在招/, 'Job cards must not claim a source-linked candidate is definitely active')
assert.match(career, /学姐记住的职业信息/, 'Users must be able to see the career facts used by the Agent')
assert.match(career, /workspace\/memory\/forget/, 'Users must be able to forget an individual Agent memory')
assert.doesNotMatch(jobSearch, /公司官网、脉脉、猎聘多平台搜索/, 'UI must not advertise an unavailable official-site provider')
assert.match(conversation, /\[5, 10, 20, 30\]/, 'Interview practice must offer 5/10/20/30 minute modes')
assert.match(conversation, /陪我热身/, 'Interview practice must offer a warm-up intensity')
assert.match(conversation, /真实强度/, 'Interview practice must offer realistic intensity')
assert.match(conversation, /压力追问/, 'Interview practice must offer pressure follow-ups')
assert.match(conversation, /给我一个救场框架/, 'Active practice must expose a non-advancing rescue scaffold')
assert.match(store, /\/rescue/, 'Interview rescue must use the structured backend endpoint')
assert.match(store, /interview\.practice\.completed/, 'Completed interview practice must be measured')
assert.match(store, /\/api\/v1\/interview\/practice\//, 'Interview answers must use the structured practice API')
assert.match(home, /今天状态怎么样/, 'Home must expose emotional check-in across the product')
assert.match(home, /昨天约定的小行动完成了吗/, 'Follow-up must ask for a real 24-hour micro-action result')
assert.match(store, /micro_action_completed:\s*microActionCompleted/, 'Micro-action completion must persist to the backend')
assert.match(conversation, /被理解了/, 'Emotional support must capture whether the user felt understood')
assert.match(store, /understood_score:\s*understoodScore/, 'Understood score must persist to the backend')
assert.doesNotMatch(store, /trackProductEvent\('emotion\.support_feedback'/, 'Support feedback must not be double-counted by client and backend')
assert.match(store, /buildTaskCompletionPrompt/, 'Completed tasks must create a natural chat follow-up instead of ending as a dead checklist')
assert.match(store, /completedAt:\s*!item\.done \? Date\.now\(\) : undefined/, 'Task completion must keep a local completion timestamp')
assert.match(store, /envVersion === 'develop'[\s\S]*__pincoSetTodayTasksForTest/, 'Synthetic task injection must be limited to WeChat develop builds')
assert.match(store, /__pincoSetTodayTasksForTest[\s\S]{0,500}setState\(\{ todayTasks: safeTasks \}\)/, 'Developer task injection must remain non-persistent')
assert.match(store, /envVersion === 'develop'[\s\S]*__pincoSetMessagesForTest/, 'Synthetic message injection must be limited to WeChat develop builds')
assert.match(store, /__pincoSetMessagesForTest[\s\S]{0,600}setState\(\{ messages: safeMessages/, 'Developer message injection must remain non-persistent')
assert.match(mine, /完成后要不要让学姐接一下/, 'Completing a task must offer a lightweight handoff back to chat')
assert.match(mine, /让学姐复盘下一步/, 'Completed task cards must keep a follow-up entry point')
assert.match(mine, /task\.action && !task\.done/, 'Completed task cards must hide the stale pre-completion action')
assert.match(home, /handleTodayTaskAction[\s\S]*task\.action === 'send_chat'/, 'Home tasks generated by triage must preserve send_chat prompts')
assert.match(home, /handleTodayTaskAction[\s\S]*task\.action === 'open_jd'/, 'Home tasks must support JD task actions')
assert.match(home, /handleTodayTaskAction[\s\S]*task\.action === 'view_progress'/, 'Home tasks must support progress task actions')
assert.match(mine, /先听我说/, 'Users must be able to choose their support style')
assert.match(mine, /允许记住倾诉正文/, 'Emotional memory must require explicit consent')
assert.match(mine, /首批用户共创/, 'First users must have an in-product design-partner feedback entry')
assert.match(mine, /professional_value_score/, 'Pilot feedback must measure professional value')
assert.match(mine, /emotional_value_score/, 'Pilot feedback must measure emotional value')
assert.match(mine, /未来 7 天，你会继续使用 Pinco 吗/, 'Pilot feedback must capture near-term return intent')
assert.match(mine, /\/api\/v1\/pilot\/feedback/, 'Pilot feedback must persist to the backend')
assert.match(store, /pending\.status === 'rejected'/, 'Job rejection must trigger a support action')
assert.match(career, /求职证据库/, 'Career evidence workspace must be available')
assert.match(career, /不得编经历|不能替你编经历|不会替你编经历/, 'Evidence workspace must state the truth boundary')
assert.doesNotMatch(career, /jd_text=\$\{encodeURIComponent\(job\.jd_text\)\}/, 'Job practice links must not embed a full JD in the WeChat navigation URL')
assert.match(career, /response\.support_action/, 'Career status changes must offer contextual emotional support')
assert.match(career, /本周 7 天证据补缺/, 'Career workspace must expose the cross-job seven-day gap plan')
assert.match(career, /workspace\/learning-plan\/progress/, 'Seven-day plan completion must persist to the backend')
assert.match(career, /匿名发布结构化复盘/, 'Completed interview reports must be able to flow back into the community')
assert.match(career, /不会公开你的原始回答、姓名或会话全文/, 'Interview report publishing must disclose its privacy boundary')
assert.match(experts, /会前摘要授权（可选）/, 'Expert context sharing must require visible per-booking consent')
assert.match(experts, /不会分享会话全文或账号数据/, 'Expert context sharing must disclose its privacy boundary')
assert.match(expertCenter, /用户已授权的会前摘要/, 'Experts must see the consented briefing before service')
assert.match(expertCenter, /用户下一步行动，每行一条/, 'Expert delivery must capture an actionable follow-up list')
assert.match(mine, /下一步 \{index \+ 1\}/, 'Buyers must receive expert next actions')
assert.match(jobSearch, /保存岗位/, 'Verified search results must flow into the job workspace')
assert.doesNotMatch(home, /navigateTo\([\s\S]{0,140}pages\/conversation\/index/, 'Home must not navigateTo the conversation tab')
assert.match(home, /switchTab\(\{ url: '\/pages\/conversation\/index'/, 'Home must switch to the conversation tab')
assert.match(home, /enterConversationWithPrompt[\s\S]{0,320}seedConversation/, 'Home quick actions must preserve their prompt across tab switching')
assert.doesNotMatch(career, /navigateTo\([\s\S]{0,140}pages\/conversation\/index/, 'Career workspace must not navigateTo the conversation tab')
assert.match(career, /practiceAgain[\s\S]{0,520}startInterview/, 'Career workspace practice must start a structured interview after tab switching')
assert.doesNotMatch(jobSearch, /navigateTo\([\s\S]{0,140}pages\/conversation\/index/, 'Job search must not navigateTo the conversation tab')
assert.match(jobSearch, /switchTab\(\{ url: '\/pages\/conversation\/index'[\s\S]{0,180}jdAnalyze\(jdContent\)/, 'Job search must preserve the selected JD when entering chat')
assert.doesNotMatch(mine, /navigateTo\([\s\S]{0,140}pages\/conversation\/index/, 'Mine must not navigateTo the conversation tab')
assert.match(mine, /openConversationTab[\s\S]{0,260}switchTab[\s\S]{0,180}seedConversation/, 'Mine must hand prompts to the conversation store when switching tabs')
assert.match(conversation, /item\.kind === 'progress'[\s\S]{0,140}navigateTo\(\{ url: '\/pages\/career\/index'/, 'Conversation progress recommendations must open the non-tab career page')
assert.match(conversation, /搜岗位[\s\S]{0,240}navigateTo\(\{ url: '\/pages\/job-search\/index'/, 'Conversation job recommendations must open the non-tab search page')

console.log('critical-flows static checks passed')
